services:
  cam:
    build: .
    volumes:
      - .:/app/
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu
    entrypoint: ["python3"]

# e.g. docker-compose run src/main.py